version: "3.8"
services:
  source:
    build: ./source_app
    hostname: source
    restart: always
    volumes:
      - ./zmq/:/zmq/
  worker:
    build: ./worker_app
    hostname: worker
    restart: always
    deploy:
      mode: replicated
      replicas: 3
    volumes:
      - ./zmq/:/zmq/
  sink:
    build: ./sink_app
    hostname: sink
    restart: always
    volumes:
      - ./zmq/:/zmq/